# Generated by Django 5.2.6 on 2025-09-18 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=255)),
                ("bio", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "website",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator()]
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator()]
                    ),
                ),
                (
                    "github",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator()]
                    ),
                ),
                ("resume", models.FileField(blank=True, upload_to="resumes/")),
                (
                    "profile_picture",
                    models.ImageField(blank=True, upload_to="profile_pics/"),
                ),
                ("current_position", models.CharField(blank=True, max_length=200)),
                (
                    "years_experience",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "education",
                    models.TextField(blank=True, help_text="Education background"),
                ),
                (
                    "certifications",
                    models.TextField(
                        blank=True, help_text="Professional certifications"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="public",
                        max_length=10,
                    ),
                ),
                ("open_to_work", models.BooleanField(default=True)),
                (
                    "preferred_salary_min",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "preferred_salary_max",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
