# Generated by Django 5.2.6 on 2025-11-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="show_certifications",
            field=models.BooleanField(
                default=True,
                help_text="Display your professional certifications",
                verbose_name="Show Certifications",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_education",
            field=models.BooleanField(
                default=True,
                help_text="Display your educational background",
                verbose_name="Show Education",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_email",
            field=models.BooleanField(
                default=True,
                help_text="Allow recruiters to see your email address",
                verbose_name="Show Email to Recruiters",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_experience",
            field=models.BooleanField(
                default=True,
                help_text="Display your work history and current position",
                verbose_name="Show Work Experience",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_links",
            field=models.BooleanField(
                default=True,
                help_text="Display your website, LinkedIn, and GitHub links",
                verbose_name="Show External Links",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_location",
            field=models.BooleanField(
                default=True,
                help_text="Display your location to recruiters",
                verbose_name="Show Location",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_phone",
            field=models.BooleanField(
                default=True,
                help_text="Display your phone number on your profile (if provided)",
                verbose_name="Show Phone Number",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_resume",
            field=models.BooleanField(
                default=True,
                help_text="Allow recruiters to download your resume",
                verbose_name="Show Resume Download",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_skills",
            field=models.BooleanField(
                default=True,
                help_text="Display your skills to recruiters",
                verbose_name="Show Skills",
            ),
        ),
    ]
