# Generated by Django 5.2.6 on 2025-11-11 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0003_profile_show_certifications_profile_show_education_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this saved search (e.g., 'Senior Python Developers in Atlanta')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of what you're looking for",
                    ),
                ),
                (
                    "search_criteria",
                    models.JSONField(
                        help_text="JSON object containing all search filters"
                    ),
                ),
                (
                    "notify_on_new_matches",
                    models.BooleanField(
                        default=True, verbose_name="Email me when new matches appear"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_match_count", models.IntegerField(default=0)),
                (
                    "recruiter",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "recruiter"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Search",
                "verbose_name_plural": "Saved Searches",
                "ordering": ["-created_at"],
            },
        ),
    ]
