# Generated by Django 5.2.6 on 2025-11-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_newmatchnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude coordinate (auto-filled from map)",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude coordinate (auto-filled from map)",
                max_digits=9,
                null=True,
            ),
        ),
    ]
