# Generated by Django 5.2.6 on 2025-09-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="salary_currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar ($)"),
                    ("EUR", "Euro (€)"),
                    ("GBP", "British Pound (£)"),
                    ("CAD", "Canadian Dollar (C$)"),
                    ("AUD", "Australian Dollar (A$)"),
                    ("JPY", "Japanese Yen (¥)"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
    ]
