# Generated by Django 5.2.6 on 2025-10-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_job_salary_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
