# Generated by Django 5.2.6 on 2025-10-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_job_latitude_job_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="location",
        ),
        migrations.AddField(
            model_name="job",
            name="city",
            field=models.CharField(
                blank=True, default="Unknown", help_text="City", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="country",
            field=models.CharField(
                default="United States", help_text="Country", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="postal_code",
            field=models.CharField(
                blank=True, help_text="Postal/Zip code", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="state_province",
            field=models.CharField(
                blank=True, help_text="State/Province", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="street_address",
            field=models.CharField(
                blank=True,
                help_text="Street address (optional for remote)",
                max_length=200,
            ),
        ),
    ]
