# Generated by Django 5.2.6 on 2025-10-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_remove_job_location_job_city_job_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="city",
            field=models.CharField(blank=True, help_text="City", max_length=100),
        ),
    ]
