# Generated by Django 5.2.6 on 2025-10-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_alter_job_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="city",
            field=models.CharField(
                blank=True, default="Atlanta", help_text="City", max_length=100
            ),
        ),
    ]
