# Generated by Django 5.2.6 on 2025-09-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("logo", models.ImageField(blank=True, upload_to="company_logos/")),
                ("location", models.CharField(blank=True, max_length=100)),
                ("founded_year", models.PositiveIntegerField(blank=True, null=True)),
                ("employees_count", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
            },
        ),
    ]
