# Generated by Django 5.2.6 on 2025-10-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_alter_company_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
