# Generated by Django 5.2.6 on 2025-09-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("application_status", "Application Status Update"),
                            ("new_job_match", "New Job Match"),
                            ("message", "New Message"),
                            ("system", "System Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("related_job_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "related_application_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
